spring:
  config:
    activate:
      on-profile: common

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 1000

# Session
server:
  servlet:
    session:
      path: /
      name: JSESSIONID
      http-only: true
      timeout: 1800

security:
  allowed-uris: /, /members/login-view, /members/login, /members/signup, /members/signup-view

mvc:
  exclude-uris: /resources/**, /members/login-view, /members/login, /members/signup, /members/signup-view