spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/store
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    market:
      book: trace

    org:
      hibernate:
        SQL: debug # 로깅으로 출력

file:
  dir: D:/test-file/